def bPsiDP24m():
    return [
         {
            "terra_swap":{
               "offer_asset_info":{
                  "token":{
                     "contract_addr":"terra1zsaswh926ey8qa5x4vj93kzzlfnef0pstuca0y"
                  }
               },
               "ask_asset_info":{
                  "token":{
                     "contract_addr":"terra12897djskt9rge8dtmm86w654g7kzckkd698608"
                  }
               }
            }
         },
         {
            "terra_swap":{
               "offer_asset_info":{
                  "token":{
                     "contract_addr":"terra12897djskt9rge8dtmm86w654g7kzckkd698608"
                  }
               },
               "ask_asset_info":{
                  "native_token":{
                     "denom":"uusd"
                  }
               }
            }
         }
      ] 