from web3 import Web3, eth

WEB3_NETWORKS_NON_ASYNC = {'bsc': { 'connection' : Web3(Web3.HTTPProvider('https://nd-718-288-301.p2pify.com/c8aa321fc47fa093d4bd974da375e863')), 'id' : 56},
                #'bsc': { 'connection' : Web3(Web3.HTTPProvider('https://bsc-dataseed.binance.org/')), 'id' : 56},
                'matic':  {'connection' : Web3(Web3.HTTPProvider('https://polygon-mainnet.infura.io/v3/d09c293e2cc14290ada8169d29e9b65f')), 'id' : 137},
                'ftm' : {'connection' : Web3(Web3.HTTPProvider('https://rpc.ftm.tools/')), 'id': 250},
                'kcc' : {'connection' : Web3(Web3.HTTPProvider('https://rpc-mainnet.kcc.network')), 'id': 321}, 
                'optimism': { 'connection' : Web3(Web3.HTTPProvider('https://optimism-mainnet.infura.io/v3/d09c293e2cc14290ada8169d29e9b65f')), 'id' : 10},
                'eth': { 'connection' : Web3(Web3.HTTPProvider('https://mainnet.infura.io/v3/d09c293e2cc14290ada8169d29e9b65f')), 'id' : 1},
                'oke': { 'connection' : Web3(Web3.HTTPProvider('https://exchainrpc.okex.org')), 'id' : 66},
                'harmony': { 'connection' : Web3(Web3.HTTPProvider('https://api.harmony.one')), 'id' : 1666600000},
                'avax': { 'connection' : Web3(Web3.HTTPProvider('https://api.avax.network/ext/bc/C/rpc')), 'id' : 43114},
                'moon': { 'connection' : Web3(Web3.HTTPProvider('https://rpc.moonriver.moonbeam.network')), 'id' : 1285},
                'arb': { 'connection' : Web3(Web3.HTTPProvider('https://arbitrum-mainnet.infura.io/v3/d09c293e2cc14290ada8169d29e9b65f')), 'id' : 42161},
                'celo': { 'connection' : Web3(Web3.HTTPProvider('https://forno.celo.org')), 'id' : 42220},
                'xdai': { 'connection' : Web3(Web3.HTTPProvider('https://rpc.xdaichain.com')), 'id' : 100},
                'heco': { 'connection' : Web3(Web3.HTTPProvider('https://http-mainnet.hecochain.com')), 'id' : 128},
                'meter': { 'connection' : Web3(Web3.HTTPProvider('https://rpc.meter.io')), 'id' : 82},
                'cro': { 'connection' : Web3(Web3.HTTPProvider('https://evm-cronos.crypto.org')), 'id' : 25},
                'polis': { 'connection' : Web3(Web3.HTTPProvider('https://rpc.polis.tech')), 'id' : 333999},
                'boba': { 'connection' : Web3(Web3.HTTPProvider('https://mainnet.boba.network/')), 'id' : 288},
                'theta': { 'connection' : Web3(Web3.HTTPProvider('https://eth-rpc-api.thetatoken.org/rpc')), 'id' : 361},
                'aurora': { 'connection' : Web3(Web3.HTTPProvider('https://mainnet.aurora.dev')), 'id' : 1313161554},             
                }

WEB3_NETWORKS = {'bsc': { 'connection' : Web3(Web3.AsyncHTTPProvider('https://nd-718-288-301.p2pify.com/c8aa321fc47fa093d4bd974da375e863'), modules={'eth': (eth.AsyncEth,)}, middlewares=[]), 'id' : 56},
                'matic':  {'connection' : Web3(Web3.AsyncHTTPProvider('https://polygon-mainnet.infura.io/v3/d09c293e2cc14290ada8169d29e9b65f'), modules={'eth': (eth.AsyncEth,)}, middlewares=[]), 'id' : 137},
                'ftm' : {'connection' : Web3(Web3.AsyncHTTPProvider('https://rpc.ftm.tools/'), modules={'eth': (eth.AsyncEth,)}, middlewares=[]), 'id': 250},
                'kcc' : {'connection' : Web3(Web3.AsyncHTTPProvider('https://rpc-mainnet.kcc.network'), modules={'eth': (eth.AsyncEth,)}, middlewares=[]), 'id': 321}, 
                'optimism': { 'connection' : Web3(Web3.AsyncHTTPProvider('https://optimism-mainnet.infura.io/v3/d09c293e2cc14290ada8169d29e9b65f'), modules={'eth': (eth.AsyncEth,)}, middlewares=[]), 'id' : 10},
                'eth': { 'connection' : Web3(Web3.AsyncHTTPProvider('https://mainnet.infura.io/v3/d09c293e2cc14290ada8169d29e9b65f'), modules={'eth': (eth.AsyncEth,)}, middlewares=[]), 'id' : 1},
                'oke': { 'connection' : Web3(Web3.AsyncHTTPProvider('https://exchainrpc.okex.org'), modules={'eth': (eth.AsyncEth,)}, middlewares=[]), 'id' : 66},
                'harmony': { 'connection' : Web3(Web3.AsyncHTTPProvider('https://api.harmony.one'), modules={'eth': (eth.AsyncEth,)}, middlewares=[]), 'id' : 1666600000},
                'avax': { 'connection' : Web3(Web3.AsyncHTTPProvider('https://api.avax.network/ext/bc/C/rpc'), modules={'eth': (eth.AsyncEth,)}, middlewares=[]), 'id' : 43114},
                'moon': { 'connection' : Web3(Web3.AsyncHTTPProvider('https://rpc.moonriver.moonbeam.network'), modules={'eth': (eth.AsyncEth,)}, middlewares=[]), 'id' : 1285},
                'arb': { 'connection' : Web3(Web3.AsyncHTTPProvider('https://arbitrum-mainnet.infura.io/v3/d09c293e2cc14290ada8169d29e9b65f'), modules={'eth': (eth.AsyncEth,)}, middlewares=[]), 'id' : 42161},                
                'celo': { 'connection' : Web3(Web3.AsyncHTTPProvider('https://forno.celo.org'), modules={'eth': (eth.AsyncEth,)}, middlewares=[]), 'id' : 42220},
                'xdai': { 'connection' : Web3(Web3.AsyncHTTPProvider('https://rpc.xdaichain.com'), modules={'eth': (eth.AsyncEth,)}, middlewares=[]), 'id' : 100},
                'heco': { 'connection' : Web3(Web3.AsyncHTTPProvider('https://http-mainnet.hecochain.com'), modules={'eth': (eth.AsyncEth,)}, middlewares=[]), 'id' : 128},
                'meter': { 'connection' : Web3(Web3.AsyncHTTPProvider('https://rpc.meter.io'), modules={'eth': (eth.AsyncEth,)}, middlewares=[]), 'id' : 82},
                'cro': { 'connection' : Web3(Web3.AsyncHTTPProvider('https://evm-cronos.crypto.org'), modules={'eth': (eth.AsyncEth,)}, middlewares=[]), 'id' : 25},
                'polis': { 'connection' : Web3(Web3.AsyncHTTPProvider('https://rpc.polis.tech'), modules={'eth': (eth.AsyncEth,)}, middlewares=[]), 'id' : 333999},
                'boba': { 'connection' : Web3(Web3.AsyncHTTPProvider('https://mainnet.boba.network/'), modules={'eth': (eth.AsyncEth,)}, middlewares=[]), 'id' : 288},
                'theta': { 'connection' : Web3(Web3.AsyncHTTPProvider('https://eth-rpc-api.thetatoken.org/rpc'), modules={'eth': (eth.AsyncEth,)}, middlewares=[]), 'id' : 361},
                'aurora': { 'connection' : Web3(Web3.AsyncHTTPProvider('https://mainnet.aurora.dev'), modules={'eth': (eth.AsyncEth,)}, middlewares=[]), 'id' : 1313161554},
                }

SCAN_APIS = {'bsc' : {'address' : 'bscscan.com', 'api_key' : '4VRVI4YKCSN4YN33MQ2BDCWXAQPHMBCZ4D', 'native_token' : '0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c_BNB_18', 'cg_name' : 'binance-smart-chain'},
'matic' : {'address' : 'polygonscan.com', 'api_key' : 'U8KZPYXSDCJQJ1S1N84Y2P3RFR78BR8AIP', 'native_token' : '0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270_MATIC_18', 'cg_name' : 'polygon-pos'},
'ftm' : {'address' : 'ftmscan.com', 'api_key' : 'J3DT48CI882HS9JX8FNVVSYFHR5UDRQZUK', 'native_token' : '0x21be370d5312f44cb42ce377bc9b8a0cef1a4c83_FTM_18', 'cg_name' : 'fantom'},
'eth' : {'address' : 'etherscan.io', 'api_key' : 'U8IWIUBBNDBJAIUIQDQMM4ITZKDATV4QYY', 'native_token' : '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2_ETH_18', 'cg_name' : 'ethereum'},
'arb' : {'address' : 'arbiscan.io', 'api_key' : 'U8IWIUBBNDBJAIUIQDQMM4ITZKDATV4QYY', 'native_token' : '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1', 'cg_name' : 'arbitrum-one'},
 }